#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

xset -b
#pulseaudio --log-level=info -D --start

numlockx &

#exec awesome
exec /usr/bin/awesome >> ~/.cache/awesome/logs/stdout 2>> ~/.cache/awesome/logs/stderr
